# Use official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /OpenSesameProject

RUN apt-get update && apt-get install -y libgomp1

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

# Run the app
CMD ["python", "-u", "main.py"]